### ISSUE TITLE
Always get same error: ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 7860)

### ISSUE THREAD

**Issue by hufuzhipeng** [chatarena/chatarena#16]
my env is win11, 
(chatarena) E:\code\ai\chatarena>conda list
# packages in environment at C:\Users\zphu\.conda\envs\chatarena:
#
# Name                    Version                   Build  Channel
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
backoff                   2.2.1                    pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2023.01.10           haa95532_0
certifi                   2022.12.7       py310haa95532_0
charset-normalizer        3.1.0                    pypi_0    pypi
chatarena                 0.1.7                    pypi_0    pypi
chess                     1.9.4                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
cohere                    4.1.4                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
farama-notifications      0.0.4                    pypi_0    pypi
fastapi                   0.95.0                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.11.0                   pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
gradio                    3.24.1                   pypi_0    pypi
gradio-client             0.0.8                    pypi_0    pypi
gymnasium                 0.28.1                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.16.3                   pypi_0    pypi
httpx                     0.23.3                   pypi_0    pypi
huggingface-hub           0.13.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
jax-jumpy                 1.0.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
libffi                    3.4.2                hd77b12b_6
linkify-it-py             2.0.0                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
openai                    0.27.4                   pypi_0    pypi
openssl                   1.1.1t               h2bbff1b_0
orjson                    3.8.10                   pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pandas                    2.0.0                    pypi_0    pypi
pettingzoo                1.22.3                   pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1          py310haa95532_0
prompt-toolkit            3.0.38                   pypi_0    pypi
pydantic                  1.10.7                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.10.10              h966fe2a_2
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rich                      13.3.3                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                65.6.3          py310haa95532_0
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.1               h2bbff1b_0
starlette                 0.26.1                   pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.27.4                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
uvicorn                   0.21.1                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.6                    pypi_0    pypi
websockets                11.0.1                   pypi_0    pypi
wheel                     0.38.4          py310haa95532_0
wincertstore              0.2             py310haa95532_2
xz                        5.2.10               h8cc25b3_1
yarl                      1.8.2                    pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0

**Comment by jimmycode** [comment]
It seems that port 7860 is not available on your machine. You can specify another port (such as 8080) in changing the last line of `app.py` to `demo.launch(debug=DEBUG, server_port=8080)` or specify environment variable GRADIO_SERVER_PORT.

Check this discussion out: https://github.com/gradio-app/gradio/discussions/109
And this doc: https://gradio.app/docs/#interface-launch
