### ISSUE TITLE
orjson package rust requirement

### ISSUE THREAD

**Issue by elliottower** [chatarena/chatarena#29]
I'm not familiar with this package but it might be worth looking into other alternatives which don't require rust, as it makes it harder to install on something like google colab (or for example, I use fish prompt on mac which had some manual installation steps required to get rust to properly work). Otherwise it should probably be in the documentation.

**Comment by DavidCincotta** [comment]
I was just having issues installing orjson with the pypy3 interpreter (3.7.11). Can anyone replicate this issue?

**Comment by yuxiang-wu** [comment]
orjson is dependency of gradio. Now this issue have been solved by making the gardio package optional dependency. You can install the chatarena with gradio extra package using command `pip install chatarena[gradio]`
