### ISSUE TITLE
Jimmy，抱歉占用了资源

### ISSUE THREAD

**Issue by Evani300** [chatarena/chatarena#34]
Jimmy，我目前在一家早期创投任职，我太喜欢你们这个仓库在做的事情了，希望有机会交流。我们一直寻找AIGC Infra层/应用层的人才，和百位来自Meta,OpenAl, Stability，Google,等公司的华人学者做过交流,加您希望能向您学习您的研究方向，一起探索商业化的可能性。这是我的联系方式wechat：c13559870609

**Comment by yuxiang-wu** [comment]
Thanks for your interest. We can chat on WeChat.
